In [1]:
import pandas as pd

In [2]:
specs = pd.read_excel('Specs.xlsx')
specs

,ID,Make,Model,Year,Front Legroom,Second Row Legroom,Combined Gas,Highway Gas,City Gas,MSRP,Car Type,Cylinders,Trim,Gwen's Choice,Image
0,1,Honda,Accord,2022,42.3,40.4,32,35,29,30470,Gas,4,FWD,Y,C:\Users\gduncan\Downloads\vroom_vroom\images\...
1,2,Honda,CRV,2023,41.3,41.0,37,34,40,36000,Hybrid,4,AWD,Y,C:\Users\gduncan\Downloads\vroom_vroom\images\...
2,3,Toyota,Highlander,2022,42.0,41.0,35,35,35,43000,Hybrid,6,AWD,Y,C:\Users\gduncan\Downloads\vroom_vroom\images\...
3,4,Tesla,Model Y,2022,41.8,40.5,125,117,131,68000,Electric,Electric,AWD,Y,C:\Users\gduncan\Downloads\vroom_vroom\images\...
4,5,Infiniti,QX60,2023,42.1,37.7,22,25,20,60000,Gas,6,AWD,Y,C:\Users\gduncan\Downloads\vroom_vroom\images\...
5,6,Cadillac,Lyriq,2023,41.4,39.6,87,82,92,64000,Electric,Electric,AWD,Y,C:\Users\gduncan\Downloads\vroom_vroom\images\...
6,7,Honda,Pilot,2022,40.9,38.4,22,19,26,51000,Gas,6,AWD,Y,C:\Users\gduncan\Downloads\vroom_vroom\images\...
7,8,Lexus,RX 350,2022,44.1,38.0,22,26,19,55000,Gas,6,AWD,Y,C:\Users\gduncan\Downloads\vroom_vroom\images\...
8,9,Nissan,Maxima,2023,45.0,34.2,24,30,20,43300,Gas,6,AWD,N,NaN
9,10,Acura,MDX,2022,41.6,38.5,21,25,19,54900,Gas,6,AWD,N,NaN
10,11,Chevrolet,Suburban,2022,44.5,42.0,17,20,15,57800,Gas,8,AWD,N,NaN
11,12,Chevrolet,Tahoe,2022,44.5,42.0,17,20,15,58100,Gas,8,AWD,N,NaN
12,13,Dodge,Charger,2022,41.8,40.1,21,27,18,38275,Gas,6,AWD,N,NaN
13,14,GMC,Yukon,2022,42.0,44.5,17,20,15,54600,Gas,8,AWD,N,NaN
14,15,Honda,Odyssey,2022,40.9,40.9,22,28,19,48770,Gas,6,FWD,N,NaN
15,16,Hyundai,Palisade,2022,44.1,42.4,21,24,19,35300,Gas,6,AWD,N,NaN
16,17,Jeep,Cherokee,2022,41.3,38.2,22,26,19,46645,Gas,6,AWD,N,NaN
17,18,Jeep,Wagoneer,2022,40.9,42.7,18,22,16,68995,Gas,8,AWD,N,NaN
18,19,Jeep,Wrangler,2022,41.2,38.3,19,23,17,39240,Gas,6,AWD,N,NaN
19,20,Kia,EV6,2022,42.4,39.0,105,94,116,51400,Electric,Electric,AWD,N,NaN
20,21,Lincoln,Aviator,2022,43.0,39.0,20,24,17,54285,Gas,6,AWD,N,NaN
21,22,Subaru,Ascent,2022,42.2,38.6,23,27,21,35295,Gas,4,AWD,N,NaN
22,23,Subaru,Forester,2022,43.3,39.4,29,33,26,32575,Gas,4,AWD,N,NaN
23,24,Tesla,Model 3,2022,42.7,35.2,113,107,118,62990,Electric,Electric,AWD,N,NaN
24,25,Tesla,Model S,2022,42.4,35.5,120,115,124,104990,Electric,Electric,AWD,N,NaN
25,26,Tesla,Model X,2022,41.1,38.7,102,97,107,120990,Electric,Electric,AWD,N,NaN
26,27,Toyota,RAV4,2022,41.0,37.8,29,33,27,32735,Gas,4,AWD,N,NaN
27,28,Toyota,Sequoia,2022,42.5,40.9,14,17,13,63830,Gas,8,AWD,N,NaN
28,29,Volkswagen,Atlas,2022,41.7,37.6,19,23,17,45855,Gas,6,AWD,N,NaN

In [3]:
cars = pd.read_csv('Cars_22-23.csv')
cars

     year      make  model body_styles
0    2022     Acura    ILX   ["Sedan"]
1    2022     Acura    MDX     ["SUV"]
2    2022     Acura    NSX   ["Coupe"]
3    2022     Acura    RDX     ["SUV"]
4    2022     Acura    TLX   ["Sedan"]
..    ...       ...    ...         ...
475  2022     Volvo   XC60     ["SUV"]
476  2022     Volvo   XC90     ["SUV"]
477  2023  Cadillac  LYRIQ     ["SUV"]
478  2023     Honda   CR-V     ["SUV"]
479  2023  INFINITI   QX60     ["SUV"]

[480 rows x 4 columns]

##### DATA CLEANING

In [4]:
#Converting year from int to string
cars['year'] = cars['year'].astype(str)
specs['Year'] = specs['Year'].astype(str)

In [5]:
#Capitalize car makes
cars['make'] = cars['make'].str.capitalize()
cars

     year      make  model body_styles
0    2022     Acura    ILX   ["Sedan"]
1    2022     Acura    MDX     ["SUV"]
2    2022     Acura    NSX   ["Coupe"]
3    2022     Acura    RDX     ["SUV"]
4    2022     Acura    TLX   ["Sedan"]
..    ...       ...    ...         ...
475  2022     Volvo   XC60     ["SUV"]
476  2022     Volvo   XC90     ["SUV"]
477  2023  Cadillac  LYRIQ     ["SUV"]
478  2023     Honda   CR-V     ["SUV"]
479  2023  Infiniti   QX60     ["SUV"]

[480 rows x 4 columns]

In [6]:
#Correct car models misspellings
cars['model'].replace(to_replace="LYRIQ",
           value="Lyriq", inplace=True)

cars['model'].replace(to_replace="CR-V",
           value="CRV", inplace=True)

cars['model'].replace(to_replace="RX",
           value="RX 350", inplace=True)
cars

     year      make  model body_styles
0    2022     Acura    ILX   ["Sedan"]
1    2022     Acura    MDX     ["SUV"]
2    2022     Acura    NSX   ["Coupe"]
3    2022     Acura    RDX     ["SUV"]
4    2022     Acura    TLX   ["Sedan"]
..    ...       ...    ...         ...
475  2022     Volvo   XC60     ["SUV"]
476  2022     Volvo   XC90     ["SUV"]
477  2023  Cadillac  Lyriq     ["SUV"]
478  2023     Honda    CRV     ["SUV"]
479  2023  Infiniti   QX60     ["SUV"]

[480 rows x 4 columns]